spring.security.user.name=olatejulian
spring.security.user.password=localtest

spring.datasource.url=jdbc:postgresql://localhost:5432/java_api_example
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.path=/docs
